name: Generate Grants
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Generate the list of grants
      run: python _scripts/generate_grants.py > ./operations/grants.rst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: ./operations/grants.rst
        ref: auto-pr/grants
        force: true
        author_name: "GitHub Actions"
        message: "update the list of grants (generated)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
