name: Main
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Lint
      run: pylama
    - name: Check broken links
      run: sphinx-build -nW -b linkcheck . _build
    - name: Generate list of grants
      run: python _scripts/generate_grants.py > ./operations/grants.rst
    - uses: EndBug/add-and-commit@v4.0.1
      with:
        add: ./operations/grants.rst
        author_name: "GitHub Actions"
        message: "generate list of grants"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
